# Generated by Django 4.2 on 2023-06-12 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='podcast_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postid', models.UUIDField(default=uuid.uuid4)),
                ('title', models.CharField(max_length=100)),
                ('thumbnail', models.FileField(upload_to='thumbnail')),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, choices=[('Audio', 'AUDIO'), ('Video', 'VIDEO')], default='', max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('speaker', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='podcast')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite_podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False)),
                ('podcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.podcast_data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
