# Generated by Django 4.2 on 2023-06-23 04:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite_podcast',
            unique_together={('user', 'podcast')},
        ),
    ]
